 const ACTIONS = {
    GET_DATA: "GET_DATA",
    GET_LIST: "GET_LIST",
    SET_WORD: "SET_WORD",
    ADD_WORD: "ADD_WORD",
    CHANGE_WORD: "CHANGE_WORD",
    DELETE_WORD: "DELETE_WORD",
    CLEAR_ALL: "CLEAR_ALL"
}

export default ACTIONS;